volumes:
  royalpong_data:
  website:

networks:
  transcendance:

services:
  backend:
    build: ./backend
    container_name: backendC
    env_file: .env
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - postgres
    networks:
      - transcendance
    volumes:
      - ./.env:/app/.env
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontendC
    volumes:
      - website:/app

  nginx:
    build: ./nginx
    container_name: nginxC
    env_file: .env
    depends_on: 
      - frontend
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    restart: always
    networks:
      - transcendance
    volumes:
      - website:/etc/nginx

  postgres:
    image: postgres:16beta1-alpine3.18
    container_name: postgresC
    env_file: .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - royalpong_data:/var/lib/postgresql/data/
    networks:
      - transcendance

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminerC
    env_file: .env
    restart: always
    ports:
      - 8080:8080
    networks:
      - transcendance

